version: 2

updates:
  #
  # .NET / NuGet
  #
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Chicago"

    open-pull-requests-limit: 5

    groups:
      dotnet-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  #
  # Frontend (npm)
  #
  - package-ecosystem: "npm"
    directory: "/src/devsecops-sentinel-web"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "America/Chicago"

    open-pull-requests-limit: 5

    groups:
      frontend-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  #
  # GitHub Actions
  #
  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "America/Chicago"

    open-pull-requests-limit: 5

    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"