<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DevSecOpsSentinel.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenAI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DevSecOpsSentinel.Application\DevSecOpsSentinel.Application.csproj" />
  </ItemGroup>
</Project>
